#include "ut.h"

int main(int argc, char **argv) {
  UtObjectRef p = ut_asn1_module_definition_parser_new();
  ut_asn1_module_definition_parser_parse(
      p, "Foo DEFINITIONS ::= \n"
         "BEGIN\n"
         "\n"
         "-- Is an integer, but > 64 bit\n"
         "CertificateSerialNumber ::= [UNIVERSAL 2] IMPLICIT OCTET STRING\n"
         "\n"
         "AlgorithmIdentifier ::= SEQUENCE {\n"
         "  algorithm   OBJECT IDENTIFIER,\n"
         "  parameters  CHOICE { null NULL, ... } OPTIONAL\n"
         "}\n"
         "\n"
         "AttributeTypeAndValue ::= SEQUENCE {"
         "  type   OBJECT IDENTIFIER,\n"
         "  value  CHOICE { null NULL, ...}\n"
         "}\n"
         "\n"
         "RelativeDistinguishedName ::= SET OF AttributeTypeAndValue\n"
         "\n"
         "Name ::= SEQUENCE OF RelativeDistinguishedName\n"
         "\n"
         "Time ::= CHOICE {\n"
         "  utcTime     UTCTime,\n"
         "  generalTime GeneralizedTime\n"
         "}\n"
         "\n"
         "Validity ::= SEQUENCE {\n"
         "  notBefore Time,\n"
         "  notAfter  Time\n"
         "}\n"
         "SubjectPublicKeyInfo ::= SEQUENCE {\n"
         "  algorithm         AlgorithmIdentifier,\n"
         "  subjectPublicKey  BIT STRING\n"
         "}\n"
         "\n"
         "UniqueIdentifier ::= BIT STRING\n"
         "\n"
         "Extension ::= SEQUENCE {\n"
         "  extnID OBJECT IDENTIFIER,\n"
         "  critical      BOOLEAN DEFAULT FALSE,\n"
         "  extnValue     OCTET STRING\n"
         "}\n"
         "\n"
         "Extensions ::= SEQUENCE OF Extension\n"
         "\n"
         "TBSCertificate ::= SEQUENCE {\n"
         "  version               [0] INTEGER DEFAULT 1,\n"
         "  serialNumber          CertificateSerialNumber,\n"
         "  signature             AlgorithmIdentifier,\n"
         "  issuer                Name,\n"
         "  validity              Validity,\n"
         "  subject               Name,\n"
         "  subjectPublicKeyInfo  SubjectPublicKeyInfo,\n"
         "  issuerUniqueID        [1] IMPLICIT UniqueIdentifier OPTIONAL,\n"
         "  subjectUniqueID       [2] IMPLICIT UniqueIdentifier OPTIONAL,\n"
         "  extensions            [3] Extensions OPTIONAL\n"
         "}\n"
         "\n"
         "Certificate ::= SEQUENCE {\n"
         "  tbsCertificate      TBSCertificate,\n"
         "  signatureAlgorithm  AlgorithmIdentifier,\n"
         "  signature           BIT STRING\n"
         "}\n"
         "\n"
         "END\n");
  ut_assert_null_object(ut_asn1_module_definition_parser_get_error(p));
  UtObject *m = ut_asn1_module_definition_parser_get_module_definition(p);
  UtObject *certificate_type =
      ut_asn1_module_definition_get_assignment(m, "Certificate");
  ut_assert_non_null_object(certificate_type);

  UtObjectRef data = ut_base64_decode(
      "MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAwTzELMAkG"
      "A1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2VhcmNoIEdyb3VwMRUw"
      "EwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4WhcNMzUwNjA0MTEwNDM4WjBP"
      "MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3Jv"
      "dXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC"
      "ggIBAK3oJHP0FDfzm54rVygch77ct984kIxuPOZXoHj3dcKi/"
      "vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+0TM8ukj13Xnfs7j/"
      "EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6UA5/"
      "TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sWT8KOEUt+"
      "zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/"
      "ELNKjD+"
      "Jo2FR3qyHB5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+"
      "UCB5iPNgiV5+I3lg02dZ77DnKxHZu8A/"
      "lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUvKBds0pjBqAlkd25HN7rOrFleaJ1/"
      "ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWnOlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+"
      "e0ocS3MFEvzG6uBQE3xDk3SzynTnjh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9"
      "gwQbooMDQaHWBfEbwrbwqHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//"
      "fb4hVC1CLQJ13hef4Y53CIrU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/"
      "wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/"
      "MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkqhkiG9w0BAQsFAAOCAgEAVR9Y"
      "qbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/"
      "V9lZLubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+"
      "EgPbk6ZGQ3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/"
      "KKNFtY2PwByVS5uCbMiogziUwthDyC3+"
      "6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5ORAzI4JMPJ+"
      "GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7UrTkXWStAmzOVyyghqpZX"
      "jFaH3pO3JLF+l+/"
      "+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdCjNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+"
      "63SM1N95R1NbdWhscdCb+ZAJzVcoyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/"
      "1lvh+wjChP4kqKOJ2qxq4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/"
      "9yi0GE44Za4rF2LN9d11TPAmRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/"
      "ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57demyPxgcYxn/eR44/"
      "KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=");
  UtObjectRef ber_decoder = ut_asn1_ber_decoder_new(data);
  UtObjectRef certificate =
      ut_asn1_decoder_decode_value(ber_decoder, certificate_type);
  ut_assert_null_object(ut_asn1_decoder_get_error(ber_decoder));
  printf("%s\n", ut_object_to_string(certificate));

  return 0;
}
