#pragma once

#define UT_TVG_MAGIC0 0x72
#define UT_TVG_MAGIC1 0x56

typedef enum {
  UT_TVG_COLOR_ENCODING_RGBA8888,
  UT_TVG_COLOR_ENCODING_RGB565,
  UT_TVG_COLOR_ENCODING_RGBA_F32,
  UT_TVG_COLOR_ENCODING_CUSTOM
} UtTvgColorEncoding;

typedef enum {
  UT_TVG_COORDINATE_RANGE_DEFAULT = 0,
  UT_TVG_COORDINATE_RANGE_REDUCED = 1,
  UT_TVG_COORDINATE_RANGE_ENHANCED = 2
} UtTvgCoordinateRange;

typedef enum {
  UT_TVG_COMMAND_END_OF_DOCUMENT = 0,
  UT_TVG_COMMAND_FILL_POLYGON = 1,
  UT_TVG_COMMAND_FILL_RECTANGLES = 2,
  UT_TVG_COMMAND_FILL_PATH = 3,
  UT_TVG_COMMAND_DRAW_LINES = 4,
  UT_TVG_COMMAND_DRAW_LINE_LOOP = 5,
  UT_TVG_COMMAND_DRAW_LINE_STRIP = 6,
  UT_TVG_COMMAND_DRAW_LINE_PATH = 7,
  UT_TVG_COMMAND_OUTLINE_FILL_POLYGON = 8,
  UT_TVG_COMMAND_OUTLINE_FILL_RECTANGLES = 9,
  UT_TVG_COMMAND_OUTLINE_FILL_PATH = 10
} UtTvgCommand;

typedef enum {
  UT_TVG_STYLE_TYPE_FLAT_COLORED = 0,
  UT_TVG_STYLE_TYPE_LINEAR_GRADIENT = 1,
  UT_TVG_STYLE_TYPE_RADIAL_GRADIENT = 2
} UtTvgStyleType;

typedef enum {
  UT_TVG_INSTRUCTION_LINE = 0,
  UT_TVG_INSTRUCTION_HORIZONTAL_LINE = 1,
  UT_TVG_INSTRUCTION_VERTICAL_LINE = 2,
  UT_TVG_INSTRUCTION_CUBIC_BEZIER = 3,
  UT_TVG_INSTRUCTION_ARC_CIRCLE = 4,
  UT_TVG_INSTRUCTION_ARC_ELLIPSE = 5,
  UT_TVG_INSTRUCTION_CLOSE_PATH = 6,
  UT_TVG_INSTRUCTION_QUADRATIC_BEZIER = 7
} UtTvgInstruction;
