name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install meson ninja-build valgrind

      - name: Meson
        run: meson _build

      - name: Test
        run: meson test -C _build --wrap='valgrind --leak-check=full --error-exitcode=1'
